### ISSUE TITLE
Recortar raster de demanda

### ISSUE THREAD

**Issue by PedroAQCoutinho** [GPP-USP/conectividade-no-campo#2]
Usando o pacote gdal, recortar o raster de demanda para a região de interesse.
Importante definir um padrão de raster para que todos fiquem alinhados.
Extensão do arquivo com o comando é .sh

**Comment by bpf-94** [comment]
Eu não conheço este tipo de extensão (.sh). 
Normalmente eu escrevo os códidos do gdal no bloco de notas e salvo como .txt
